/**
 * Integration tests for Story 7.5: 与现有执行/导出工具链的集成
 * 
 * Validates that specs generated by `autoqa plan` can be:
 * 1. Parsed by parseMarkdownSpec (used by autoqa run)
 * 2. Executed by autoqa run without modification
 * 3. Exported to Playwright Test via Epic 4 pipeline
 */
import { describe, it, expect } from 'vitest'
import { parseMarkdownSpec } from '../../src/markdown/parse-markdown-spec.js'
import { buildMarkdownForTestCase } from '../../src/plan/output.js'
import type { TestCasePlan } from '../../src/plan/types.js'

describe('Plan Integration with Run and Export', () => {
  describe('AC1: Generated specs satisfy autoqa run input constraints', () => {
    it('should generate valid markdown that parseMarkdownSpec accepts', () => {
      const testCase: TestCasePlan = {
        id: 'case-1',
        name: 'Login with valid credentials',
        type: 'form',
        priority: 'p0',
        relatedPageIds: ['login', 'dashboard'],
        markdownPath: 'auth/login.md',
        preconditions: ['User has a valid account', 'Application is accessible'],
        steps: [
          {
            description: 'Navigate to {{BASE_URL}}/login',
            expectedResult: 'Login page is displayed',
          },
          {
            description: 'Fill username field with {{USERNAME}}',
            expectedResult: 'Username is entered',
          },
          {
            description: 'Fill password field with {{PASSWORD}}',
            expectedResult: 'Password is entered',
          },
          {
            description: 'Click the "Login" button',
            expectedResult: 'User is redirected to dashboard',
          },
          {
            description: 'Verify the page shows "Welcome"',
            expectedResult: 'Welcome message is visible',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      expect(parseResult.value.preconditions).toHaveLength(2)
      expect(parseResult.value.preconditions[0]).toBe('User has a valid account')
      expect(parseResult.value.steps).toHaveLength(5)
      expect(parseResult.value.steps[0].text).toContain('Navigate to')
      expect(parseResult.value.steps[4].kind).toBe('assertion')
    })

    it('should generate specs with template variables that preserve {{VAR}} format', () => {
      const testCase: TestCasePlan = {
        id: 'case-2',
        name: 'Navigate with base URL',
        type: 'navigation',
        priority: 'p1',
        relatedPageIds: ['home'],
        markdownPath: 'navigation/base-url.md',
        preconditions: ['Environment variables are configured'],
        steps: [
          {
            description: 'Navigate to {{BASE_URL}}',
            expectedResult: 'Home page loads',
          },
          {
            description: 'Navigate to {{LOGIN_BASE_URL}}/auth',
            expectedResult: 'Auth page loads',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)

      // Verify template variables are preserved in markdown
      expect(markdown).toContain('{{BASE_URL}}')
      expect(markdown).toContain('{{LOGIN_BASE_URL}}')

      // Verify parseMarkdownSpec can handle it
      const parseResult = parseMarkdownSpec(markdown)
      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      expect(parseResult.value.steps[0].text).toContain('{{BASE_URL}}')
      expect(parseResult.value.steps[1].text).toContain('{{LOGIN_BASE_URL}}')
    })

    it('should generate specs with default preconditions when none provided', () => {
      const testCase: TestCasePlan = {
        id: 'case-3',
        name: 'Basic navigation test',
        type: 'functional',
        priority: 'p2',
        relatedPageIds: ['home'],
        markdownPath: 'basic.md',
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      // Should have default precondition
      expect(parseResult.value.preconditions).toHaveLength(1)
      expect(parseResult.value.preconditions[0]).toContain('Base URL accessible: {{BASE_URL}}')

      // Should have default step
      expect(parseResult.value.steps).toHaveLength(1)
      expect(parseResult.value.steps[0].text).toContain('Navigate to {{BASE_URL}}/')
    })

    it('should classify steps correctly as actions or assertions', () => {
      const testCase: TestCasePlan = {
        id: 'case-4',
        name: 'Mixed actions and assertions',
        type: 'functional',
        priority: 'p1',
        relatedPageIds: ['home'],
        markdownPath: 'mixed.md',
        preconditions: ['App is running'],
        steps: [
          {
            description: 'Navigate to /products',
            expectedResult: 'Products page loads',
          },
          {
            description: 'Click the "Add to Cart" button',
            expectedResult: 'Item is added',
          },
          {
            description: 'Verify the page shows "1 item in cart"',
            expectedResult: 'Cart count is updated',
          },
          {
            description: 'Assert that "Checkout" button is visible',
            expectedResult: 'Checkout button appears',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      // First two are actions
      expect(parseResult.value.steps[0].kind).toBe('action')
      expect(parseResult.value.steps[1].kind).toBe('action')
      
      // Last two are assertions (start with Verify/Assert)
      expect(parseResult.value.steps[2].kind).toBe('assertion')
      expect(parseResult.value.steps[3].kind).toBe('assertion')
    })

    it('should handle Chinese step descriptions', () => {
      const testCase: TestCasePlan = {
        id: 'case-5',
        name: '中文测试用例',
        type: 'functional',
        priority: 'p1',
        relatedPageIds: ['home'],
        markdownPath: 'chinese.md',
        preconditions: ['应用程序正在运行'],
        steps: [
          {
            description: '导航到 /login',
            expectedResult: '登录页面显示',
          },
          {
            description: '验证页面显示 "欢迎"',
            expectedResult: '欢迎消息可见',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      expect(parseResult.value.steps[0].kind).toBe('action')
      expect(parseResult.value.steps[1].kind).toBe('assertion')
    })
  })

  describe('AC2: Generated specs work with Epic 5 template variables', () => {
    it('should preserve template variables for environment variable substitution', () => {
      const testCase: TestCasePlan = {
        id: 'case-6',
        name: 'Login with environment credentials',
        type: 'form',
        priority: 'p0',
        relatedPageIds: ['login'],
        markdownPath: 'auth/env-login.md',
        preconditions: ['AUTOQA_USERNAME and AUTOQA_PASSWORD are set'],
        steps: [
          {
            description: 'Navigate to {{BASE_URL}}/login',
            expectedResult: 'Login form is visible',
          },
          {
            description: 'Fill username with {{USERNAME}}',
            expectedResult: 'Username is entered',
          },
          {
            description: 'Fill password with {{PASSWORD}}',
            expectedResult: 'Password is entered',
          },
          {
            description: 'Click submit button',
            expectedResult: 'User is logged in',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)

      // Verify all template variables are preserved
      expect(markdown).toContain('{{BASE_URL}}')
      expect(markdown).toContain('{{USERNAME}}')
      expect(markdown).toContain('{{PASSWORD}}')

      // Verify markdown is parseable
      const parseResult = parseMarkdownSpec(markdown)
      expect(parseResult.ok).toBe(true)
    })
  })

  describe('AC3: Generated specs compatible with Epic 4 export pipeline', () => {
    it('should generate specs that match expected structure for IR/export', () => {
      const testCase: TestCasePlan = {
        id: 'case-7',
        name: 'Exportable test case',
        type: 'form',
        priority: 'p0',
        relatedPageIds: ['login'],
        markdownPath: 'export/login.md',
        preconditions: ['Application is accessible'],
        steps: [
          {
            description: 'Navigate to /login',
            expectedResult: 'Login page loads',
          },
          {
            description: 'Fill the "username" field with "testuser"',
            expectedResult: 'Username is entered',
          },
          {
            description: 'Fill the "password" field with "testpass"',
            expectedResult: 'Password is entered',
          },
          {
            description: 'Click the "Login" button',
            expectedResult: 'Login is submitted',
          },
          {
            description: 'Verify the page shows "Dashboard"',
            expectedResult: 'Dashboard page is displayed',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      // Verify structure matches what export pipeline expects
      expect(parseResult.value.preconditions.length).toBeGreaterThan(0)
      expect(parseResult.value.steps.length).toBeGreaterThan(0)

      // Verify steps have clear action descriptions that can be mapped to tools
      const navigateStep = parseResult.value.steps[0]
      expect(navigateStep.text.toLowerCase()).toContain('navigate')

      const fillSteps = parseResult.value.steps.filter(s => s.text.toLowerCase().includes('fill'))
      expect(fillSteps.length).toBe(2)

      const clickStep = parseResult.value.steps.find(s => s.text.toLowerCase().includes('click'))
      expect(clickStep).toBeDefined()

      const assertionStep = parseResult.value.steps.find(s => s.kind === 'assertion')
      expect(assertionStep).toBeDefined()
    })

    it('should not include planner-specific metadata in spec markdown', () => {
      const testCase: TestCasePlan = {
        id: 'case-8',
        name: 'Test without metadata pollution',
        type: 'functional',
        priority: 'p1',
        relatedPageIds: ['page-1', 'page-2'],
        markdownPath: 'clean.md',
        preconditions: ['App is ready'],
        steps: [
          {
            description: 'Navigate to /test',
            expectedResult: 'Page loads',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)

      // Verify no planner-specific metadata leaks into spec
      expect(markdown).not.toContain('relatedPageIds')
      expect(markdown).not.toContain('page-1')
      expect(markdown).not.toContain('case-8')
      
      // Should only contain standard spec sections
      expect(markdown).toContain('# Test without metadata pollution')
      expect(markdown).toContain('## Preconditions')
      expect(markdown).toContain('## Steps')
      expect(markdown).toContain('Type: functional')
      expect(markdown).toContain('Priority: P1')
    })
  })

  describe('Edge cases and error handling', () => {
    it('should handle empty steps array gracefully', () => {
      const testCase: TestCasePlan = {
        id: 'case-9',
        name: 'Empty steps test',
        type: 'functional',
        priority: 'p2',
        relatedPageIds: ['home'],
        markdownPath: 'empty.md',
        preconditions: ['App is running'],
        steps: [],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      // Should still be parseable with default step
      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      expect(parseResult.value.steps).toHaveLength(1)
      expect(parseResult.value.steps[0].text).toContain('Navigate to {{BASE_URL}}/')
    })

    it('should handle steps with special characters', () => {
      const testCase: TestCasePlan = {
        id: 'case-10',
        name: 'Special characters test',
        type: 'functional',
        priority: 'p2',
        relatedPageIds: ['home'],
        markdownPath: 'special.md',
        preconditions: ['App is running'],
        steps: [
          {
            description: 'Navigate to /search?q=test&filter=all',
            expectedResult: 'Search results appear',
          },
          {
            description: 'Click the "Save & Continue" button',
            expectedResult: 'Progress is saved',
          },
          {
            description: 'Verify the page shows "Success! (100%)"',
            expectedResult: 'Success message is visible',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      expect(parseResult.value.steps[0].text).toContain('?q=test&filter=all')
      expect(parseResult.value.steps[1].text).toContain('Save & Continue')
      expect(parseResult.value.steps[2].text).toContain('Success! (100%)')
    })
  })
})
